_extends: .github
name-template: '$RESOLVED_VERSION'
tag-template: 'taglist-maven-plugin-$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '📦 Dependency updates'
    labels:
      - 'dependencies'
  - title: '⚠️ Deprecations'
    labels:
      - 'deprecation'
  - title: '⛔ Removed features'
    labels:
      - 'removal'
      - 'removed'
  - title: '🧰 Maintenance'
    labels:
      - 'chore'
      - 'build'
version-resolver:
  major:
    labels:
      - major
  minor:
    labels:
      - minor
      - enhancement
  patch:
    labels:
      - patch
  default: patch
template: |
  ## Changes
  
  $CHANGES
